from __future__ import annotations

from collections.abc import Iterable

from app.domain.enums import CapabilityArchetype
from app.extensions.schemas import (
    AgentRegistrySnapshot,
    AgentSpec,
    AgentType,
    ExtensionManagerSnapshot,
    ExtensionStatus,
    PackRegistrySnapshot,
    PackSpec,
    PackType,
)


def build_pack_catalog() -> list[PackSpec]:
    return [
        PackSpec(
            pack_id="operations_pack",
            pack_type=PackType.DOMAIN,
            pack_name="Operations Pack",
            description="營運治理、流程瓶頸、交付能力、資源配置與執行節奏的顧問工作模組。",
            domain_definition="用於判斷企業的 operating model、流程設計、跨部門 handoff、服務或履約能力、資源配置與執行節奏是否足以支撐目前的成長與交付要求。",
            common_problem_patterns=[
                "流程 bottleneck 導致交付延遲、品質波動或內部重工",
                "創辦人或少數核心成員過度承擔營運協調，無法形成可複製流程",
                "擴張後 handoff 增加，但 SOP、責任邊界與容量規劃未同步建立",
                "需求成長快於服務 / 履約 / support capacity，導致客訴或 churn",
                "部門各自優化局部效率，但整體 throughput 與決策速度反而下降",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "先確認核心交付流程是否能穩定重複，而不是過早堆疊太多產品線或制度。",
                    "創業階段的營運問題通常不是 SOP 太少，而是流程責任仍綁在創辦人腦中。",
                ],
                "制度化階段": [
                    "重點是 handoff、容量、SOP、例外處理與管理節奏是否已被制度化。",
                    "若營收成長但交付品質與速度不穩，通常應先做 operating model hardening。",
                ],
                "規模化階段": [
                    "規模化階段要優先檢查跨團隊協調、授權邏輯與 bottleneck ownership，而不是只增加人力。",
                    "若流程治理仍靠人盯人，規模化會快速放大 hidden dependency 與 rework。",
                ],
            },
            key_kpis_or_operating_signals=[
                "cycle time / lead time",
                "throughput / backlog",
                "on-time delivery rate",
                "capacity utilization",
                "fulfillment or service SLA",
                "rework / defect / complaint rate",
                "support backlog aging",
            ],
            key_kpis=[
                "cycle time / lead time",
                "throughput / backlog",
                "on-time delivery rate",
                "capacity utilization",
                "fulfillment or service SLA",
                "rework / defect / complaint rate",
                "support backlog aging",
            ],
            domain_lenses=["operations"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務", "自媒體"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "operating model diagnosis",
                "execution readiness",
                "process bottleneck review",
                "resource sequencing",
            ],
            evidence_expectations=[
                "流程圖、SOP、責任分工與 handoff 說明",
                "產能、人力、排程、履約或服務交付資料",
                "backlog、交付延遲、客訴、返工與品質訊號",
                "例外處理方式、跨部門協作節點與瓶頸說明",
            ],
            risk_libraries=[
                "delivery risk",
                "dependency risk",
                "throughput risk",
                "quality slippage risk",
            ],
            common_risks=[
                "hidden bottleneck 由少數人承擔，擴張時會先斷在關鍵 handoff",
                "流程文件存在但不被使用，造成治理表面化",
                "容量規劃落後需求成長，導致交付品質與客戶體驗惡化",
                "過度客製或例外處理侵蝕整體效率與利潤",
            ],
            decision_patterns=[
                "是否先修 bottleneck 再擴量",
                "是否該標準化流程或保留高彈性例外處理",
                "是否該先補人、補系統還是重做 handoff 與 ownership",
                "是否該調整服務 / 履約承諾以匹配實際容量",
            ],
            recommendation_patterns=[
                "execution sequence",
                "operating model adjustment",
                "constraint mitigation",
                "capacity and SLA hardening",
            ],
            deliverable_presets=[
                "operations assessment memo",
                "process bottleneck review",
                "execution roadmap",
                "operating model hardening brief",
            ],
            routing_hints=[
                "operations",
                "process",
                "execution",
                "workflow",
                "營運",
                "流程",
                "交付",
                "履約",
                "sop",
                "handoff",
            ],
            pack_notes=[
                "Operations Pack 要先回答系統能不能穩定做成，而不是先回答市場願不願意買單。",
            ],
            scope_boundaries=[
                "不負責決定品牌定位、訊息策略或渠道投放細節，這應由 Marketing / Sales Pack 主導。",
                "不負責資本結構、募資與財務可行性收斂，這應由 Finance / Fundraising Pack 主導。",
                "不應被用來替代法遵、責任條款或契約邊界判斷。",
            ],
            pack_rationale=[
                "這個 pack 必須獨立存在，因為大量企業問題表面看似策略或成長，底層其實卡在 operating model 與 execution capacity。",
                "若把它併進 Strategy 或 Marketing，系統容易只給方向建議，卻忽略真正的交付與流程瓶頸。",
                "它最常出現在 SOP 重整、交付品質波動、跨部門協作失靈、擴張前的容量診斷等顧問任務。",
                "若定義太窄，系統會錯過營運治理的核心缺口；若定義太廣，又會吞掉財務、法務與商業成長問題。",
            ],
        ),
        PackSpec(
            pack_id="finance_fundraising_pack",
            pack_type=PackType.DOMAIN,
            pack_name="Finance / Fundraising Pack",
            description="財務結構、現金流、單位經濟、資金規劃與募資決策的顧問工作模組。",
            domain_definition="用於判斷企業的 revenue model、成本結構、現金流、單位經濟、資本配置與募資 readiness 是否足以支撐目前策略與成長路徑。",
            common_problem_patterns=[
                "營收看似成長，但實際現金流、毛利或營運資金壓力正在惡化",
                "團隊想加碼成長或擴編，但尚未確認 burn、runway 與回收節奏是否可承受",
                "募資或對外溝通看起來完整，但 underlying assumptions 與 data room 基礎不足",
                "單位經濟與產品 / 客群 / 通路策略不一致，導致資源配置失真",
                "財務資訊存在，但還不能支撐真正的決策與資金優先順序",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "先確認 runway、burn 與第一性單位經濟是否站得住，再討論更大規模的資金投入。",
                    "創業階段的財務資料常不完整，重點是辨識關鍵假設與現金壓力，而不是追求報表完美。",
                ],
                "制度化階段": [
                    "應把預算紀律、現金流預測、產品 / 客群毛利結構與回本週期視為核心治理指標。",
                    "若募資敘事與內部財務事實不一致，應先修正數據邏輯而不是重寫 pitch。",
                ],
                "規模化階段": [
                    "規模化階段要優先檢查資本配置、working capital、部門資源配置與 growth efficiency。",
                    "如果成長建立在低品質營收或高額現金消耗上，應先收斂投資節奏。",
                ],
            },
            key_kpis_or_operating_signals=[
                "gross margin / contribution margin",
                "burn rate / runway",
                "cash conversion cycle",
                "working capital pressure",
                "CAC payback / LTV:CAC",
                "forecast accuracy",
                "fundraising timeline and data room readiness",
            ],
            key_kpis=[
                "gross margin / contribution margin",
                "burn rate / runway",
                "cash conversion cycle",
                "working capital pressure",
                "CAC payback / LTV:CAC",
                "forecast accuracy",
                "fundraising timeline and data room readiness",
            ],
            domain_lenses=["finance", "fundraising"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務", "自媒體"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "capital planning",
                "unit economics review",
                "fundraising readiness",
                "cash discipline and allocation decision",
            ],
            evidence_expectations=[
                "財務報表、管理報表、現金流與預算資料",
                "收入 / 毛利 / 成本拆解與單位經濟假設",
                "pipeline、forecast、營運資金與收付款節奏資料",
                "募資 deck、data room、cap table 與 investor Q&A 材料",
            ],
            risk_libraries=[
                "cash risk",
                "capital structure risk",
                "fundraising risk",
                "assumption quality risk",
            ],
            common_risks=[
                "runway 被高估或 burn 被低估",
                "單位經濟看似成立，但未反映真實回本週期與服務成本",
                "募資材料可講故事，但數據與假設無法支撐盡調",
                "working capital 與付款條件壓力被忽略，導致成長越快越缺錢",
            ],
            decision_patterns=[
                "是否該先控 burn、先補現金流治理還是直接啟動募資",
                "是否該調整價格、產品組合或客群結構來改善單位經濟",
                "是否該採用 equity、debt 或 bridge 形式補資金",
                "是否該收斂投資節奏，把資源集中到回收最快的部分",
            ],
            recommendation_patterns=[
                "capital allocation",
                "funding strategy",
                "financial discipline",
                "runway protection sequence",
            ],
            deliverable_presets=[
                "finance assessment memo",
                "fundraising decision brief",
                "cash discipline review",
                "unit economics diagnostic",
            ],
            routing_hints=[
                "finance",
                "fundraising",
                "cash flow",
                "capital",
                "runway",
                "burn",
                "募資",
                "財務",
                "現金流",
                "預算",
            ],
            pack_notes=[
                "Finance / Fundraising Pack 的重點不是把財務資料做漂亮，而是回答這個策略是否撐得住、資金怎麼配才合理。",
            ],
            scope_boundaries=[
                "不負責最終法律文件意見、投資契約條款或法遵認定，這應由 Legal / Risk Pack 主導。",
                "不負責品牌定位或 campaign 執行細節，這應由 Marketing / Sales Pack 主導。",
                "不應被用來取代營運流程診斷或組織治理設計。",
            ],
            pack_rationale=[
                "這個 pack 必須獨立存在，因為很多決策不是『想不想做』，而是『資金與經濟性是否允許做』。",
                "若把它併進一般策略或營運 pack，系統容易忽略現金流、工作資本與募資 readiness 的硬邊界。",
                "它最常出現在資金規劃、財務診斷、成長投資評估、募資準備與單位經濟收斂等顧問任務。",
                "若定義太窄，會只剩募資工具；若定義太廣，又會把營運、法務與商業成長問題一起吞掉。",
            ],
        ),
        PackSpec(
            pack_id="legal_risk_pack",
            pack_type=PackType.DOMAIN,
            pack_name="Legal / Risk Pack",
            description="法務邊界、契約條款、合規責任與正式風險挑戰的顧問工作模組。",
            domain_definition="用於判斷企業在契約、法遵、責任分配、資料與合規要求、交易風險與 governance 邊界上，哪些事項會實質影響這次判斷與交付。",
            common_problem_patterns=[
                "商業討論已往前推進，但契約責任、權利義務與 liability 分配尚未被看清",
                "團隊以為只是營運或商務問題，實際上高風險點來自法遵、條款或資料處理義務",
                "對外合作、代理、通路或募資安排在 legal boundary 上仍有大量灰區",
                "文件存在，但風險條款、附件缺漏與義務落點尚未被整理成可採取行動的風險視圖",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "創業階段常見問題不是文件太少，而是關鍵條款、責任邊界與資料處理習慣尚未建立。",
                    "應先抓高風險條款、責任不對稱與是否需要 escalation，而不是追求法律文件完備感。",
                ],
                "制度化階段": [
                    "制度化階段要把契約模板、法遵流程、授權邏輯與例外審批節點建立起來。",
                    "若商務擴張快於法遵治理，風險通常會在合作、個資與責任分配上爆出來。",
                ],
                "規模化階段": [
                    "規模化階段重點是法遵治理與風險分類，而不只是單一文件 redline。",
                    "當合作數量、地區與產品複雜度上升時，要先辨識哪些風險需要標準化管理。",
                ],
            },
            key_kpis_or_operating_signals=[
                "material clause exposure",
                "compliance incident frequency",
                "unresolved redline count",
                "obligation concentration",
                "data / privacy handling coverage",
                "escalation turnaround",
            ],
            key_kpis=[
                "material clause exposure",
                "compliance incident frequency",
                "unresolved redline count",
                "obligation concentration",
                "data / privacy handling coverage",
                "escalation turnaround",
            ],
            domain_lenses=["legal", "risk"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務", "自媒體"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "contract review",
                "risk challenge",
                "compliance review",
                "obligation boundary check",
            ],
            evidence_expectations=[
                "合約、條款、附件、redline 與版本比對資料",
                "法遵政策、授權流程、資料處理與內部治理材料",
                "交易對手要求、責任分工與既有例外處理紀錄",
            ],
            risk_libraries=[
                "contractual risk",
                "liability risk",
                "compliance risk",
                "governance gap risk",
            ],
            common_risks=[
                "責任不對稱與 indemnity / liability 暴露",
                "附件、定義、驗收條件或 termination 邏輯缺漏",
                "資料處理、隱私、宣稱或授權流程不完整",
                "商務承諾已超過法律或合規可承受邊界",
            ],
            decision_patterns=[
                "是否接受、要求 redline、升級法務或暫停推進",
                "是否需要重寫責任分配、交付定義或驗收條件",
                "是否要建立額外合規流程、授權層級或風險揭露",
                "是否能以風險接受換取商業利益，還是應直接排除",
            ],
            recommendation_patterns=[
                "redline recommendation",
                "risk mitigation",
                "clarification request",
                "escalation recommendation",
            ],
            deliverable_presets=[
                "review memo",
                "risk brief",
                "redline summary",
                "compliance gap review",
            ],
            routing_hints=[
                "legal",
                "contract",
                "risk",
                "compliance",
                "法務",
                "合約",
                "條款",
                "責任",
                "個資",
                "法遵",
            ],
            pack_notes=[
                "Legal / Risk Pack 的任務不是把所有問題法律化，而是辨識真正會改變決策邊界的條款、責任與合規風險。",
            ],
            scope_boundaries=[
                "不取代正式法律意見或執業律師的最終判斷。",
                "不負責品牌、成長或商務拓展策略本身，除非那些策略已碰到明確法律邊界。",
                "不應被用來代替財務可行性或營運落地診斷。",
            ],
            pack_rationale=[
                "這個 pack 必須獨立存在，因為 legal / compliance / liability 風險常常會直接改寫可行方案。",
                "若把它併進一般風險或營運 pack，系統容易把高法律風險誤降成一般執行提醒。",
                "它最常出現在合約審閱、合作條款、資料合規、權利義務盤點與風險挑戰類顧問任務。",
                "若定義太窄，只剩 redline；若定義太廣，又會把所有商業不確定性都塞成 legal issue。",
            ],
        ),
        PackSpec(
            pack_id="marketing_sales_pack",
            pack_type=PackType.DOMAIN,
            pack_name="Marketing / Sales Pack",
            description="市場定位、需求生成、商業漏斗、成交流程與 GTM 收斂的顧問工作模組。",
            domain_definition="用於判斷企業的市場定位、訊息、需求生成、渠道、商機漏斗、成交流程與 commercial traction 是否成立，以及應優先修哪一段商業路徑。",
            common_problem_patterns=[
                "有流量但沒有成交，或有成交但商機品質不穩",
                "訊息與受眾不匹配，導致 conversion 卡在漏斗上游或中段",
                "行銷與銷售分工斷裂，導致 pipeline 看起來有量但無法轉為現金",
                "成長依賴單一渠道、單一 campaign 或創辦人個人銷售能力",
                "團隊同時想修品牌、內容、廣告、銷售流程，但不知道先修哪一段",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "創業階段優先驗證定位、訊息與首條可重複獲客路徑，而不是同時鋪很多渠道。",
                    "若還無法說清楚誰會買、為什麼買，應先補 message-market fit 而不是擴投。",
                ],
                "制度化階段": [
                    "制度化階段要把 MQL / SQL / pipeline / close 的定義與 handoff 做清楚。",
                    "若表面有 lead 但成交效率差，通常要同時檢查訊息、offer 與 sales process。",
                ],
                "規模化階段": [
                    "規模化階段要優先檢查 channel mix、pipeline quality 與 CAC 回收，不是只堆更多流量。",
                    "成長放大前應先確認 sales enablement、內容系統與 attribution 不會一起失真。",
                ],
            },
            key_kpis_or_operating_signals=[
                "lead-to-opportunity conversion",
                "opportunity-to-close / win rate",
                "sales cycle length",
                "pipeline coverage",
                "CAC / CPL / channel efficiency",
                "average deal size",
                "message-to-conversion drop-off",
            ],
            key_kpis=[
                "lead-to-opportunity conversion",
                "opportunity-to-close / win rate",
                "sales cycle length",
                "pipeline coverage",
                "CAC / CPL / channel efficiency",
                "average deal size",
                "message-to-conversion drop-off",
            ],
            domain_lenses=["marketing", "sales"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務", "自媒體"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "go-to-market decision",
                "message-market fit",
                "funnel diagnosis",
                "commercial traction review",
            ],
            evidence_expectations=[
                "受眾與 ICP 定義、定位、訊息與 offer 材料",
                "campaign 資料、流量來源、landing page 與轉換漏斗",
                "CRM / pipeline / 通話紀錄 / 銷售提案與 objection patterns",
                "客戶訪談、贏單 / 失單原因與留存 / 擴張訊號",
            ],
            risk_libraries=[
                "channel risk",
                "conversion risk",
                "message risk",
                "pipeline quality risk",
            ],
            common_risks=[
                "渠道依賴或買量效率惡化",
                "定位與訊息不清，導致高流量低成交",
                "銷售流程不穩，導致 pipeline 失真或成交高度依賴個人",
                "行銷與銷售目標不一致，造成獲客與成交脫節",
            ],
            decision_patterns=[
                "是否先修定位 / 訊息還是先修漏斗 / 銷售流程",
                "是否該集中渠道、收斂 offer 或調整 ICP",
                "是否該優先提高 conversion / win rate，而不是直接擴大投放",
                "是否需要重新設計 GTM sequencing 與 sales enablement",
            ],
            recommendation_patterns=[
                "positioning refinement",
                "funnel adjustment",
                "sales enablement",
                "channel prioritization",
            ],
            deliverable_presets=[
                "growth brief",
                "GTM decision memo",
                "funnel diagnosis review",
                "commercial traction memo",
            ],
            routing_hints=[
                "marketing",
                "sales",
                "growth",
                "GTM",
                "行銷",
                "銷售",
                "漏斗",
                "pipeline",
                "廣告",
                "成交",
                "定位",
            ],
            pack_notes=[
                "Marketing / Sales Pack 的重點是找出哪一段商業路徑最該優先修，而不是把所有成長問題都丟給流量。",
            ],
            scope_boundaries=[
                "不負責策略聯盟、通路合作與 partnership structure 的主判斷，這應由 Business Development Pack 主導。",
                "不負責最終法遵與契約風險邊界，這應由 Legal / Risk Pack 主導。",
                "不應被用來替代營運交付能力與容量診斷。",
            ],
            pack_rationale=[
                "這個 pack 必須獨立存在，因為大量顧問案件的核心問題其實是 demand generation、訊息與成交路徑沒有接起來。",
                "若把它併進一般策略或商務開發，系統容易忽略 funnel、conversion 與 commercial process 的細節。",
                "它最常出現在 GTM、漏斗診斷、定位重整、商業敘事修正與 sales enablement 類任務。",
                "若定義太窄，會只剩 marketing campaign；若定義太廣，會把 partnership、營運與財務問題一起吞掉。",
            ],
        ),
        PackSpec(
            pack_id="business_development_pack",
            pack_type=PackType.DOMAIN,
            pack_name="Business Development Pack",
            description="策略合作、通路拓展、夥伴結構、商務機會開發與 ecosystem 動態的顧問工作模組。",
            domain_definition="用於判斷企業是否應透過 partnerships、代理 / 經銷、通路合作、策略聯盟、共同銷售或大型商務開發來推進成長，以及該如何設計合作結構。",
            common_problem_patterns=[
                "團隊知道要找合作夥伴，但不知道該找哪一類 partner、怎麼排序、怎麼談結構",
                "現有商務合作看似有量，實際 partner-sourced pipeline 品質與轉換偏弱",
                "渠道 / 經銷 / 聯盟與直營銷售互相打架，導致責任與誘因扭曲",
                "大型 deal、合作提案或通路拓展缺少明確的商務判斷框架",
                "公司把所有對外拓展都當成 sales，卻忽略生態位、合作可持續性與治理成本",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "創業階段應先確認 partnership 是否真能降低獲客成本或提高信任，不要為了『看起來大』而談合作。",
                    "初期商務合作最常失敗在價值交換不清楚，而不是 partner 數量太少。",
                ],
                "制度化階段": [
                    "制度化階段要把 direct、channel、referral、alliance 的角色與分潤機制講清楚。",
                    "若 partner-sourced pipeline 很大但 close 不好，應先回頭檢查 partner qualification 與 enablement。",
                ],
                "規模化階段": [
                    "規模化階段要優先檢查 partner concentration、territory conflict 與 governance model。",
                    "商務拓展若沒有 account ownership 與 enablement 制度，擴大合作只會放大混亂。",
                ],
            },
            key_kpis_or_operating_signals=[
                "partner-sourced pipeline",
                "partner activation rate",
                "channel conversion / close rate",
                "average deal cycle",
                "partner concentration",
                "account coverage / expansion",
                "joint pipeline quality",
            ],
            key_kpis=[
                "partner-sourced pipeline",
                "partner activation rate",
                "channel conversion / close rate",
                "average deal cycle",
                "partner concentration",
                "account coverage / expansion",
                "joint pipeline quality",
            ],
            domain_lenses=["business_development", "sales"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "partnership evaluation",
                "channel expansion",
                "deal shaping",
                "ecosystem strategy review",
            ],
            evidence_expectations=[
                "合作提案、LOI、分潤結構與 partner profile",
                "partner-sourced pipeline、成交資料與 enablement materials",
                "直營 / 渠道衝突、account mapping 與 territory 資訊",
                "商務合作的 unit economics、治理機制與資源投入估算",
            ],
            risk_libraries=[
                "partner dependency risk",
                "deal execution risk",
                "channel conflict risk",
                "ecosystem governance risk",
            ],
            common_risks=[
                "過度依賴單一 partner 或單一通路",
                "合作結構看似有量，但激勵錯配導致 pipeline 品質差",
                "channel 與 direct sales conflict 侵蝕團隊內部效率",
                "合作案需要的管理成本高於實際商業回報",
            ],
            decision_patterns=[
                "是否該用 partnership 還是直營來擴市場",
                "是否該優先做 referral、reseller、alliance 或 strategic account",
                "是否該調整 deal structure、分潤與 ownership",
                "是否該縮減低品質合作，把資源集中到高價值 partner",
            ],
            recommendation_patterns=[
                "partner strategy",
                "deal structure recommendation",
                "channel prioritization",
                "ecosystem governance design",
            ],
            deliverable_presets=[
                "business development brief",
                "partnership review memo",
                "channel strategy memo",
                "ecosystem decision brief",
            ],
            routing_hints=[
                "partnership",
                "business development",
                "channel",
                "alliance",
                "partner",
                "商務開發",
                "合作",
                "通路",
                "代理",
                "聯盟",
            ],
            pack_notes=[
                "Business Development Pack 的重點是判斷合作結構與生態位是否成立，而不是把所有 BD 問題都簡化成 sales pipeline。",
            ],
            scope_boundaries=[
                "不負責 demand gen、內容投放與訊息優化主判斷，這應由 Marketing / Sales Pack 主導。",
                "不取代法務對合作契約、責任條款與合規邊界的審閱。",
                "不應被用來替代財務現金流與資本配置判斷。",
            ],
            pack_rationale=[
                "這個 pack 必須獨立存在，因為 partnership / channel / alliance 類決策與一般 marketing 或 direct sales 的邏輯不同。",
                "若把它併進 Marketing / Sales Pack，系統容易忽略合作結構、partner incentives 與 ecosystem dynamics。",
                "它最常出現在策略合作、渠道設計、經銷拓展、enterprise partnership 與大型商務案 shaping。",
                "若定義太窄，會只剩 partner list；若定義太廣，會把行銷、銷售、法務與財務問題混成同一包。",
            ],
        ),
        PackSpec(
            pack_id="research_intelligence_pack",
            pack_type=PackType.DOMAIN,
            pack_name="Research / Intelligence Pack",
            description="市場情報、外部訊號、競爭情報、研究綜整與不確定性盤點的顧問工作模組。",
            domain_definition="用於判斷這次任務是否需要以研究、外部訊號、競爭情報、情境盤點與 evidence synthesis 為核心，並把雜訊整理成可支撐判斷的 intelligence view。",
            common_problem_patterns=[
                "使用者問題很重要，但目前內部資料薄弱，需要先做外部態勢或市場情報盤點",
                "資訊很多但來源分散、時效不一、觀點互相衝突，還沒有被整理成 decision-grade synthesis",
                "團隊需要競品、產業、政策或市場變化的整理，但不應假裝已經有 company-specific certainty",
                "已有研究資料，但缺少真正能拿去做決策的 pattern、gap 與 next questions",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "創業階段的研究任務應先回答市場是否值得切入、誰的問題最痛、哪些假設最值得先驗證。",
                    "若資料稀疏，應優先形成 exploratory brief，而不是假裝能直接下完整營運結論。",
                ],
                "制度化階段": [
                    "制度化階段的 intelligence 重點通常是競爭格局、訊號品質與策略選項比較。",
                    "研究若不能回到決策與資源配置，通常只會形成看過就算的摘要。",
                ],
                "規模化階段": [
                    "規模化階段應把市場變動、競爭反應、監管與情境差異當作高優先 intelligence inputs。",
                    "當公司跨市場或跨產品線時，研究工作要更重視 scenario comparison 與 signal recency。",
                ],
            },
            key_kpis_or_operating_signals=[
                "source coverage breadth",
                "signal recency",
                "evidence convergence / divergence",
                "competitive move frequency",
                "market growth / contraction signals",
                "customer insight density",
                "research gap count",
            ],
            key_kpis=[
                "source coverage breadth",
                "signal recency",
                "evidence convergence / divergence",
                "competitive move frequency",
                "market growth / contraction signals",
                "customer insight density",
                "research gap count",
            ],
            domain_lenses=["research", "intelligence"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務", "自媒體"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "market scan",
                "situation assessment",
                "signal synthesis",
                "research gap framing",
            ],
            evidence_expectations=[
                "外部公開來源、新聞、政策、競品資訊與研究報告",
                "客戶訪談、用戶回饋、社群討論或需求訊號",
                "時序性資料、情境比較與 conflicting signals",
                "研究假設、來源品質說明與仍待驗證的 gap",
            ],
            risk_libraries=[
                "signal ambiguity",
                "recency risk",
                "information quality risk",
                "false certainty risk",
            ],
            common_risks=[
                "來源看起來很多，但其實 recency 或品質不足",
                "把外部訊號誤當成 company-specific certainty",
                "研究輸出停留在摘錄，沒有形成決策意義",
                "過度依賴單一報告、單一觀點或單一競品訊號",
            ],
            decision_patterns=[
                "是否已足以形成 exploratory brief、assessment memo 或 scenario comparison",
                "是否需要補更多研究，或已可收斂成決策問題",
                "是否該把外部態勢拆成共通已知與公司待驗證兩層",
                "是否該先辨識 research gaps 再下行動建議",
            ],
            recommendation_patterns=[
                "research brief",
                "situation framing",
                "further inquiry guidance",
                "signal quality clarification",
            ],
            deliverable_presets=[
                "exploratory brief",
                "research memo",
                "situation assessment",
                "signal convergence review",
            ],
            routing_hints=[
                "research",
                "intelligence",
                "signals",
                "market",
                "研究",
                "情報",
                "競品",
                "市場",
                "趨勢",
                "政策",
            ],
            pack_notes=[
                "Research / Intelligence Pack 的重點是把不完整世界整理成可判斷的 evidence view，而不是堆更多摘要。",
            ],
            scope_boundaries=[
                "不直接取代 Operations、Finance 或 Marketing / Sales 的專業判斷，只提供 intelligence 與 evidence synthesis。",
                "不應把外部研究直接包裝成公司內部已確認事實。",
                "不負責最終法律意見或契約 redline 主判斷。",
            ],
            pack_rationale=[
                "這個 pack 必須獨立存在，因為真實顧問工作裡有大量任務的第一步其實是先把世界看清楚，而不是直接給方案。",
                "若把它併進一般策略或市場 pack，系統容易把 research quality、source recency 與 uncertainty governance 忽略掉。",
                "它最常出現在市場盤點、競品研究、政策 / 產業變化判讀、external-research-heavy sparse cases 與高層 intelligence brief。",
                "若定義太窄，會只剩資料摘錄；若定義太廣，會把最終決策與執行方案也混進研究工作裡。",
            ],
        ),
        PackSpec(
            pack_id="online_education_pack",
            pack_type=PackType.INDUSTRY,
            pack_name="Online Education Pack",
            description="Learning-business context for digital courses, cohorts, tutoring, memberships, and education delivery systems.",
            industry_definition="For businesses monetizing structured learning outcomes through digital courses, cohorts, tutoring, memberships, or B2B education products.",
            common_business_models=[
                "一次性課程銷售",
                "cohort / bootcamp",
                "會員訂閱",
                "顧問式教學 / tutoring",
                "B2B 教育授權",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "先驗證學習成果與招生訊息是否能形成穩定轉單。",
                    "優先辨識課程完成率與退款風險，而不是過早擴大內容產品線。",
                ],
                "制度化階段": [
                    "重點檢查招生漏斗、課程交付 SOP 與講師 / 助教產能。",
                    "應把續購與完成率視為比表面營收更重要的健康訊號。",
                ],
                "規模化階段": [
                    "優先檢查 cohort 擴張是否壓縮教學品質與 support capacity。",
                    "B2C 與 B2B 教育產品線應分開評估其交付與銷售節奏。",
                ],
            },
            key_kpis=[
                "lead-to-enrollment conversion",
                "trial / webinar-to-sale conversion",
                "course completion rate",
                "learner retention / repeat purchase",
                "refund rate",
                "contribution margin per cohort",
            ],
            domain_lenses=["marketing", "sales", "operations"],
            relevant_client_types=["個人品牌與服務", "自媒體", "中小企業"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "course portfolio decision",
                "learner funnel diagnosis",
                "pricing and cohort model review",
            ],
            evidence_expectations=[
                "招生漏斗資料",
                "課程完成率與續購資料",
                "產品組合與定價材料",
                "學員回饋 / NPS / 客訴訊號",
                "內容交付與講師產能資料",
            ],
            risk_libraries=["completion risk", "refund risk", "instructor dependency risk"],
            common_risks=[
                "過度依賴單一講師或創辦人",
                "招生成本高於終身價值",
                "完成率偏低導致口碑與續購受損",
                "退款 / 課程體驗風險放大",
                "平台與流量依賴",
            ],
            decision_patterns=[
                "是否應調整課程 / cohort 組合",
                "是否應重設定價與升級路徑",
                "是否應優先優化招生漏斗或教學完成率",
                "是否應從 B2C 擴到 B2B / 授權模式",
            ],
            recommendation_patterns=[
                "learner funnel adjustment",
                "curriculum portfolio reprioritization",
                "delivery capacity hardening",
            ],
            deliverable_presets=[
                "online education growth brief",
                "learner funnel review memo",
                "course portfolio decision memo",
            ],
            routing_hints=[
                "線上教育",
                "線上課程",
                "課程",
                "教學",
                "補教",
                "cohort",
                "bootcamp",
                "tutoring",
                "education",
                "edtech",
                "學員",
                "招生",
            ],
            pack_notes=[
                "對教育型生意，不能只看營收，還要同步檢查完成率、退款與交付品質。",
            ],
        ),
        PackSpec(
            pack_id="ecommerce_pack",
            pack_type=PackType.INDUSTRY,
            pack_name="Ecommerce Pack",
            description="Commerce context for direct-to-consumer, marketplace, social commerce, and omnichannel selling models.",
            industry_definition="For businesses selling physical or digital goods through owned stores, marketplaces, social commerce, or omnichannel operations.",
            common_business_models=[
                "DTC 自營電商",
                "平台型電商 / marketplace",
                "社群電商 / 直播帶貨",
                "訂閱制補貨",
                "零售批發混合通路",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "先確認核心 SKU、價格帶與主要通路是否成立。",
                    "不應只看 GMV，必須同步檢查單筆訂單貢獻毛利。",
                ],
                "制度化階段": [
                    "重點是回購、SKU 毛利、庫存週轉與履約穩定度。",
                    "通路擴張前應先確認促銷依賴是否已侵蝕毛利與品牌定位。",
                ],
                "規模化階段": [
                    "應優先檢查 channel mix、需求預測與廣告效率，而不是只追求更多營收。",
                    "跨通路經營時要把平台依賴與供應鏈壓力視為高優先風險。",
                ],
            },
            key_kpis=[
                "conversion rate",
                "average order value",
                "repeat purchase rate",
                "contribution margin",
                "CAC / MER / ROAS",
                "return rate",
                "inventory turns",
            ],
            domain_lenses=["marketing", "sales", "operations", "finance"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "channel mix decision",
                "SKU and margin diagnosis",
                "retention versus acquisition prioritization",
            ],
            evidence_expectations=[
                "通路 / 流量與轉換漏斗",
                "SKU 毛利與退貨資料",
                "客單與回購 cohort",
                "存貨周轉與履約資料",
                "平台 / 廣告依賴資料",
            ],
            risk_libraries=["channel dependency risk", "inventory risk", "margin compression risk"],
            common_risks=[
                "廣告成本惡化",
                "單一平台依賴",
                "SKU 組合與庫存錯配",
                "退貨侵蝕毛利",
                "促銷依賴造成品牌與利潤受損",
            ],
            decision_patterns=[
                "是否該調整通路 mix",
                "是否該集中 SKU 與價格帶",
                "是否優先提升回購而非買量",
                "是否該重做促銷與會員策略",
            ],
            recommendation_patterns=[
                "channel prioritization",
                "SKU portfolio rationalization",
                "retention-first growth sequence",
            ],
            deliverable_presets=[
                "ecommerce operating review",
                "commerce channel decision memo",
                "SKU and margin brief",
            ],
            routing_hints=[
                "電商",
                "ecommerce",
                "shopify",
                "商城",
                "購物車",
                "dtc",
                "蝦皮",
                "momo",
                "平台電商",
                "商品",
                "sku",
                "履約",
            ],
            pack_notes=[
                "電商案件應同時看通路、毛利、庫存與回購，不可只看流量與營收表面成長。",
            ],
        ),
        PackSpec(
            pack_id="gaming_pack",
            pack_type=PackType.INDUSTRY,
            pack_name="Gaming Pack",
            description="Gaming context for launch readiness, live ops, player retention, monetization design, and portfolio volatility.",
            industry_definition="For game studios, publishers, and live-ops businesses monetizing player engagement through premium, free-to-play, service, or hybrid models.",
            common_business_models=[
                "Premium 遊戲銷售",
                "Free-to-play + IAP",
                "廣告變現",
                "訂閱 / season pass",
                "發行 / 聯運 / IP 授權",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "應先確認核心玩法與留存是否成立，避免在 retention 未過關前過早放大 UA。",
                    "首款產品應優先驗證玩家黏著與變現假設，而不是只追求下載量。",
                ],
                "制度化階段": [
                    "要把 live ops 節奏、內容產能與 monetization loop 一起檢查。",
                    "若同時經營多平台或多作品，應先釐清作品組合的資源分配。",
                ],
                "規模化階段": [
                    "應把 portfolio risk、平台政策與內容 cadence 視為核心治理議題。",
                    "擴大投放與跨區發行前，必須確認 retention 與 payer economics 是否穩定。",
                ],
            },
            key_kpis=[
                "D1 / D7 / D30 retention",
                "DAU / MAU",
                "payer conversion",
                "ARPDAU / ARPPU",
                "CPI versus LTV",
                "content cadence health",
                "wishlists / launch conversion",
            ],
            domain_lenses=["marketing", "operations", "finance", "research"],
            relevant_client_types=["中小企業", "大型企業"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "launch readiness review",
                "live ops prioritization",
                "monetization and retention trade-off",
            ],
            evidence_expectations=[
                "留存 cohort",
                "付費與虛寶資料",
                "UA / CPI / ROAS",
                "live ops 節奏與活動資料",
                "玩家評價與社群訊號",
                "平台檔期與商店頁資料",
            ],
            risk_libraries=["retention risk", "platform risk", "portfolio volatility risk"],
            common_risks=[
                "留存不足導致買量失效",
                "內容更新節奏跟不上",
                "平台政策或商店檔期風險",
                "付費設計引發玩家反彈",
                "單一作品依賴與 hit-driven 波動",
            ],
            decision_patterns=[
                "是否該優先改善留存還是買量",
                "是否該調整 monetization loop",
                "是否適合做 live ops / content cadence investment",
                "是否該採 premium / F2P / hybrid 路線",
            ],
            recommendation_patterns=[
                "retention-first launch sequence",
                "live ops calendar prioritization",
                "monetization risk mitigation",
            ],
            deliverable_presets=[
                "gaming live-ops brief",
                "game launch readiness memo",
                "player economy risk review",
            ],
            routing_hints=[
                "遊戲",
                "gaming",
                "game",
                "玩家",
                "live ops",
                "steam",
                "app store",
                "google play",
                "課金",
                "retention",
                "發行",
                "wishlist",
            ],
            pack_notes=[
                "遊戲案件應先判斷 retention / monetization / content cadence 三者是否同時成立，再談規模化買量。",
            ],
        ),
        PackSpec(
            pack_id="funeral_services_pack",
            pack_type=PackType.INDUSTRY,
            pack_name="Funeral Services Pack",
            description="Funeral and memorial service context where trust, compliance, referral channels, and operational sensitivity dominate decisions.",
            industry_definition="For funeral, memorial, and bereavement service businesses where service trust, compliance, referral channels, and operational sensitivity matter.",
            common_business_models=[
                "單次禮儀 / 喪葬服務",
                "套裝儀式服務",
                "生前契約 / pre-need",
                "殯儀轉介與合作通路",
                "塔位 / 周邊紀念服務",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "應先確認服務信任、轉介來源與成交流程是否穩定。",
                    "在初期擴張前，需先確保資訊揭露與服務品質一致。",
                ],
                "制度化階段": [
                    "重點是接案到交付 SOP、報價透明度與人力排程能力。",
                    "應把 pre-need、轉介結構與方案毛利一起看，而非只看案量。",
                ],
                "規模化階段": [
                    "擴點或擴服務前，需先檢查品牌信任與法遵風險是否可複製管理。",
                    "轉介與合作通路集中度應被視為高優先風險。",
                ],
            },
            key_kpis=[
                "lead-to-case conversion",
                "average case value",
                "package mix margin",
                "referral source concentration",
                "service capacity utilization",
                "pre-need attach / conversion",
                "customer complaint rate",
            ],
            domain_lenses=["operations", "legal", "sales"],
            relevant_client_types=["中小企業", "大型企業"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "service package design",
                "referral channel dependency review",
                "service trust and SOP hardening",
            ],
            evidence_expectations=[
                "服務流程與轉介來源",
                "方案組合與報價資料",
                "個案量與人力排程",
                "法遵 / 契約 / 資訊揭露材料",
                "客訴與口碑訊號",
            ],
            risk_libraries=["reputation risk", "compliance risk", "capacity risk"],
            common_risks=[
                "信任與聲譽損傷",
                "法遵或資訊揭露風險",
                "過度依賴單一轉介來源",
                "旺淡季與人力容量錯配",
                "價格不透明導致成交與口碑受損",
            ],
            decision_patterns=[
                "是否該重整服務組合與報價架構",
                "是否該降低轉介依賴",
                "是否該優先強化 pre-need 模式",
                "是否該補強接案到交付的服務 SOP",
            ],
            recommendation_patterns=[
                "service package redesign",
                "referral diversification",
                "trust and compliance hardening",
            ],
            deliverable_presets=[
                "funeral services operating memo",
                "service trust risk brief",
                "referral channel review",
            ],
            routing_hints=[
                "殯葬",
                "禮儀",
                "葬儀",
                "funeral",
                "memorial",
                "喪葬",
                "生前契約",
                "塔位",
                "殯儀",
            ],
            pack_notes=[
                "喪葬服務案件需要把信任、法遵、轉介結構與人力容量一起視為核心決策條件。",
            ],
        ),
        PackSpec(
            pack_id="health_supplements_pack",
            pack_type=PackType.INDUSTRY,
            pack_name="Health Supplements Pack",
            description="Supplement and nutraceutical context where claims compliance, repeat purchase, trust, and SKU economics are core.",
            industry_definition="For health supplement and nutraceutical businesses where claims compliance, repeat purchase, trust, channel mix, and SKU economics are core.",
            common_business_models=[
                "DTC 保健品牌",
                "訂閱補貨",
                "平台電商銷售",
                "藥局 / 零售通路",
                "代工 / 聯名 / 專業通路合作",
            ],
            stage_specific_heuristics={
                "創業階段": [
                    "應先確認核心產品主張、法規可行性與首批回購是否成立。",
                    "初期不宜同時擴太多 SKU 與通路，避免庫存與訊息分散。",
                ],
                "制度化階段": [
                    "重點是 SKU 貢獻毛利、回購 cohort、claim 合規與通路效率。",
                    "若投放成長建立在低回購之上，應優先修正產品與 retention 而非加碼買量。",
                ],
                "規模化階段": [
                    "擴大通路前，必須先管理效期、品質信任與廣告 / 平台政策風險。",
                    "品牌規模化要把合規、供應鏈與客訴機制一起納入治理。",
                ],
            },
            key_kpis=[
                "repeat purchase rate",
                "subscription retention",
                "average order value",
                "contribution margin by SKU",
                "inventory expiry / turns",
                "CAC / MER / ROAS",
                "refund / complaint rate",
            ],
            domain_lenses=["marketing", "sales", "finance", "legal"],
            relevant_client_types=["中小企業", "大型企業", "個人品牌與服務"],
            relevant_client_stages=["創業階段", "制度化階段", "規模化階段"],
            default_decision_context_patterns=[
                "SKU portfolio decision",
                "claim and compliance review",
                "channel and retention prioritization",
            ],
            evidence_expectations=[
                "SKU 組合與回購 cohort",
                "法規 / 成分 / claim 材料",
                "通路與廣告表現",
                "評價與退貨 / 客訴資料",
                "庫存週轉與效期資料",
            ],
            risk_libraries=["claim compliance risk", "channel dependency risk", "inventory expiry risk"],
            common_risks=[
                "功效宣稱或法遵風險",
                "廣告與平台政策風險",
                "SKU 複雜度造成庫存壓力",
                "低回購導致 CAC 無法回收",
                "品質信任事件放大",
            ],
            decision_patterns=[
                "是否該集中明星 SKU",
                "是否該調整 claim 與訊息策略",
                "是否優先做訂閱 / 回購而非買量",
                "是否該重整通路與投放配置",
                "是否需先補強 compliance 與品質信任",
            ],
            recommendation_patterns=[
                "hero SKU focus",
                "compliance-first messaging",
                "retention before acquisition scale-up",
            ],
            deliverable_presets=[
                "supplements growth memo",
                "claim and channel risk review",
                "SKU portfolio decision brief",
            ],
            routing_hints=[
                "保健食品",
                "保健",
                "健康食品",
                "supplement",
                "supplements",
                "nutraceutical",
                "維他命",
                "益生菌",
                "魚油",
                "膠原",
            ],
            pack_notes=[
                "保健品案件不應只看流量與營收，必須把回購、claim 合規、品質信任與 SKU 結構一起看。",
            ],
        ),
    ]


def build_agent_catalog() -> list[AgentSpec]:
    return [
        AgentSpec(
            agent_id="host_agent",
            agent_name="Host Agent",
            agent_type=AgentType.HOST,
            description="The only orchestration center. Frames decisions, resolves packs, selects agents, governs readiness, and converges deliverables.",
            supported_capabilities=list(CapabilityArchetype),
            input_requirements=["DecisionContext", "Context spine", "Pack resolver outputs", "Evidence"],
            output_contract=["Capability frame", "Readiness governance", "Deliverable convergence"],
            invocation_rules=["Always present", "Cannot be disabled while the system is active"],
            escalation_rules=["Escalate missing-world-state ambiguity before claiming high-confidence decisions"],
        ),
        AgentSpec(
            agent_id="strategy_decision_agent",
            agent_name="Strategy / Decision Agent",
            agent_type=AgentType.REASONING,
            description="Handles framing, option comparison, prioritization, and decision convergence.",
            supported_capabilities=[
                CapabilityArchetype.DIAGNOSE_ASSESS,
                CapabilityArchetype.DECIDE_CONVERGE,
                CapabilityArchetype.SCENARIO_COMPARISON,
                CapabilityArchetype.RISK_SURFACING,
            ],
            relevant_domain_packs=["operations_pack", "finance_fundraising_pack", "marketing_sales_pack"],
            input_requirements=["DecisionContext", "Evidence", "Goals", "Constraints"],
            output_contract=["Insights", "Options", "Recommendations"],
            invocation_rules=["Prefer for cross-functional decision framing"],
            escalation_rules=["Escalate when no coherent decision context can be framed"],
        ),
        AgentSpec(
            agent_id="operations_agent",
            agent_name="Operations Agent",
            agent_type=AgentType.REASONING,
            description="Evaluates feasibility, process implications, dependencies, and execution sequencing.",
            supported_capabilities=[
                CapabilityArchetype.DIAGNOSE_ASSESS,
                CapabilityArchetype.DECIDE_CONVERGE,
                CapabilityArchetype.PLAN_ROADMAP,
                CapabilityArchetype.RISK_SURFACING,
            ],
            relevant_domain_packs=["operations_pack"],
            relevant_industry_packs=[
                "online_education_pack",
                "ecommerce_pack",
                "funeral_services_pack",
            ],
            input_requirements=["Evidence", "Constraints", "Artifacts"],
            output_contract=["Operational insights", "Risks", "Action items"],
            invocation_rules=["Prefer when execution design or operating model implications matter"],
            escalation_rules=["Escalate if core process evidence is missing"],
        ),
        AgentSpec(
            agent_id="finance_agent",
            agent_name="Finance Agent",
            agent_type=AgentType.REASONING,
            description="Handles economics, capital, cash flow, and fundraising-oriented reasoning.",
            supported_capabilities=[
                CapabilityArchetype.DIAGNOSE_ASSESS,
                CapabilityArchetype.DECIDE_CONVERGE,
                CapabilityArchetype.PLAN_ROADMAP,
                CapabilityArchetype.SCENARIO_COMPARISON,
            ],
            relevant_domain_packs=["finance_fundraising_pack"],
            relevant_industry_packs=[
                "ecommerce_pack",
                "gaming_pack",
                "health_supplements_pack",
                "online_education_pack",
            ],
            input_requirements=["Financial artifacts", "Assumptions", "Evidence"],
            output_contract=["Financial insights", "Risks", "Recommendations"],
            invocation_rules=["Prefer when capital, pricing, or economics are decision-critical"],
            escalation_rules=["Escalate if financial assumptions are missing or contradictory"],
        ),
        AgentSpec(
            agent_id="legal_risk_agent",
            agent_name="Legal / Risk Agent",
            agent_type=AgentType.REASONING,
            description="Surfaces legal boundaries, compliance risks, and contract-related implications.",
            supported_capabilities=[
                CapabilityArchetype.REVIEW_CHALLENGE,
                CapabilityArchetype.RISK_SURFACING,
                CapabilityArchetype.DECIDE_CONVERGE,
            ],
            relevant_domain_packs=["legal_risk_pack"],
            relevant_industry_packs=[
                "funeral_services_pack",
                "health_supplements_pack",
                "gaming_pack",
            ],
            input_requirements=["Artifacts", "Evidence", "Constraints"],
            output_contract=["Risk surfacing", "Recommendations", "Issue summaries"],
            invocation_rules=["Prefer when legal exposure or governance matters"],
            escalation_rules=["Escalate if required legal materials are missing"],
        ),
        AgentSpec(
            agent_id="marketing_growth_agent",
            agent_name="Marketing / Growth Agent",
            agent_type=AgentType.REASONING,
            description="Analyzes positioning, acquisition, demand shaping, and growth narratives.",
            supported_capabilities=[
                CapabilityArchetype.DIAGNOSE_ASSESS,
                CapabilityArchetype.SYNTHESIZE_BRIEF,
                CapabilityArchetype.DECIDE_CONVERGE,
                CapabilityArchetype.PLAN_ROADMAP,
            ],
            relevant_domain_packs=["marketing_sales_pack"],
            relevant_industry_packs=[
                "online_education_pack",
                "ecommerce_pack",
                "gaming_pack",
                "health_supplements_pack",
            ],
            input_requirements=["Audience signals", "Artifacts", "External research"],
            output_contract=["Growth insights", "Recommendations", "Narrative risks"],
            invocation_rules=["Prefer when market-facing messaging or acquisition is core"],
            escalation_rules=["Escalate if audience evidence is too sparse for specific claims"],
        ),
        AgentSpec(
            agent_id="sales_business_development_agent",
            agent_name="Sales / Business Development Agent",
            agent_type=AgentType.REASONING,
            description="Assesses pipeline, commercial motion, partnerships, and opportunity development.",
            supported_capabilities=[
                CapabilityArchetype.DIAGNOSE_ASSESS,
                CapabilityArchetype.DECIDE_CONVERGE,
                CapabilityArchetype.PLAN_ROADMAP,
                CapabilityArchetype.SCENARIO_COMPARISON,
            ],
            relevant_domain_packs=["marketing_sales_pack", "business_development_pack"],
            relevant_industry_packs=[
                "online_education_pack",
                "ecommerce_pack",
                "funeral_services_pack",
            ],
            input_requirements=["Commercial artifacts", "Evidence", "Goals"],
            output_contract=["Commercial options", "Action items", "Risks"],
            invocation_rules=["Prefer when GTM, pipeline, or partnership choices are central"],
            escalation_rules=["Escalate if pipeline reality and goals are badly misaligned"],
        ),
        AgentSpec(
            agent_id="research_intelligence_agent",
            agent_name="Research / Intelligence Agent",
            agent_type=AgentType.REASONING,
            description="Synthesizes external signals, research inputs, and multi-source evidence into decision-useful frames.",
            supported_capabilities=[
                CapabilityArchetype.SYNTHESIZE_BRIEF,
                CapabilityArchetype.DIAGNOSE_ASSESS,
                CapabilityArchetype.SCENARIO_COMPARISON,
                CapabilityArchetype.RISK_SURFACING,
            ],
            relevant_domain_packs=["research_intelligence_pack"],
            relevant_industry_packs=[
                "online_education_pack",
                "ecommerce_pack",
                "gaming_pack",
                "funeral_services_pack",
                "health_supplements_pack",
            ],
            input_requirements=["Source materials", "Evidence", "DecisionContext"],
            output_contract=["Synthesis briefs", "Evidence summaries", "Uncertainty framing"],
            invocation_rules=["Prefer for external-research-heavy or sparse-input cases"],
            escalation_rules=["Escalate if source quality is too weak to support claims"],
        ),
        AgentSpec(
            agent_id="document_communication_agent",
            agent_name="Document / Communication Agent",
            agent_type=AgentType.REASONING,
            description="Shapes documents, narratives, drafts, and communication-oriented deliverables.",
            supported_capabilities=[
                CapabilityArchetype.RESTRUCTURE_REFRAME,
                CapabilityArchetype.SYNTHESIZE_BRIEF,
                CapabilityArchetype.PLAN_ROADMAP,
            ],
            relevant_domain_packs=["marketing_sales_pack"],
            relevant_industry_packs=[
                "online_education_pack",
                "funeral_services_pack",
                "health_supplements_pack",
            ],
            input_requirements=["Artifacts", "Audience", "Goals"],
            output_contract=["Restructured drafts", "Communication recommendations", "Audience-aware deliverables"],
            invocation_rules=["Prefer when artifact restructuring or narrative shaping is required"],
            escalation_rules=["Escalate if target audience or deliverable purpose is missing"],
        ),
        AgentSpec(
            agent_id="contract_review_specialist",
            agent_name="Contract Review Specialist",
            agent_type=AgentType.SPECIALIST,
            description="Document-centered specialist for contract review, clause risk surfacing, and redline-oriented outputs.",
            supported_capabilities=[CapabilityArchetype.REVIEW_CHALLENGE],
            relevant_domain_packs=["legal_risk_pack"],
            input_requirements=["Contract artifact", "Supporting evidence"],
            output_contract=["High-risk clauses", "Redline recommendations", "Missing items"],
            invocation_rules=["Prefer for single-document legal review tasks"],
            escalation_rules=["Escalate if contract attachments are missing"],
        ),
        AgentSpec(
            agent_id="research_synthesis_specialist",
            agent_name="Research Synthesis Specialist",
            agent_type=AgentType.SPECIALIST,
            description="Evidence-heavy specialist for synthesizing research materials into a decision-useful brief.",
            supported_capabilities=[CapabilityArchetype.SYNTHESIZE_BRIEF],
            relevant_domain_packs=["research_intelligence_pack"],
            input_requirements=["Source materials", "Evidence", "DecisionContext"],
            output_contract=["Findings", "Implications", "Research gaps"],
            invocation_rules=["Prefer for multi-source research synthesis"],
            escalation_rules=["Escalate if evidence coverage is too thin for conclusions"],
        ),
        AgentSpec(
            agent_id="document_restructuring_specialist",
            agent_name="Document Restructuring Specialist",
            agent_type=AgentType.SPECIALIST,
            description="Artifact-centered specialist for restructuring proposals, memos, and drafts for a target audience.",
            supported_capabilities=[CapabilityArchetype.RESTRUCTURE_REFRAME],
            relevant_domain_packs=["marketing_sales_pack"],
            relevant_industry_packs=[
                "online_education_pack",
                "funeral_services_pack",
                "health_supplements_pack",
            ],
            input_requirements=["Artifact", "Audience", "Goal"],
            output_contract=["Restructuring strategy", "Structure adjustments", "Draft outline"],
            invocation_rules=["Prefer for single-document restructuring tasks"],
            escalation_rules=["Escalate if source document purpose is unclear"],
        ),
    ]


class ExtensionRegistry:
    def __init__(self) -> None:
        self._packs = {pack.pack_id: pack for pack in build_pack_catalog()}
        self._agents = {agent.agent_id: agent for agent in build_agent_catalog()}
        host_agents = [
            agent.agent_id
            for agent in self._agents.values()
            if agent.agent_type == AgentType.HOST and agent.status == ExtensionStatus.ACTIVE
        ]
        if len(host_agents) != 1:
            raise ValueError("ExtensionRegistry requires exactly one active Host Agent.")
        self._host_agent_id = host_agents[0]

    def list_packs(self, pack_type: PackType | None = None) -> list[PackSpec]:
        packs = list(self._packs.values())
        if pack_type is not None:
            packs = [pack for pack in packs if pack.pack_type == pack_type]
        return sorted(packs, key=lambda item: (item.pack_type.value, item.pack_id))

    def get_pack(self, pack_id: str) -> PackSpec | None:
        return self._packs.get(pack_id)

    def list_agents(self, agent_type: AgentType | None = None) -> list[AgentSpec]:
        agents = list(self._agents.values())
        if agent_type is not None:
            agents = [agent for agent in agents if agent.agent_type == agent_type]
        return sorted(agents, key=lambda item: (item.agent_type.value, item.agent_id))

    def get_agent(self, agent_id: str) -> AgentSpec | None:
        return self._agents.get(agent_id)

    def get_host_agent(self) -> AgentSpec:
        return self._agents[self._host_agent_id]

    def pack_registry_snapshot(self) -> PackRegistrySnapshot:
        packs = self.list_packs()
        return PackRegistrySnapshot(
            packs=packs,
            active_pack_ids=[pack.pack_id for pack in packs if pack.status == ExtensionStatus.ACTIVE],
            draft_pack_ids=[pack.pack_id for pack in packs if pack.status == ExtensionStatus.DRAFT],
            inactive_pack_ids=[
                pack.pack_id
                for pack in packs
                if pack.status in {ExtensionStatus.INACTIVE, ExtensionStatus.DEPRECATED}
            ],
        )

    def agent_registry_snapshot(self) -> AgentRegistrySnapshot:
        agents = self.list_agents()
        return AgentRegistrySnapshot(
            agents=agents,
            host_agent_id=self._host_agent_id,
            active_agent_ids=[agent.agent_id for agent in agents if agent.status == ExtensionStatus.ACTIVE],
            draft_agent_ids=[agent.agent_id for agent in agents if agent.status == ExtensionStatus.DRAFT],
            inactive_agent_ids=[
                agent.agent_id
                for agent in agents
                if agent.status in {ExtensionStatus.INACTIVE, ExtensionStatus.DEPRECATED}
            ],
        )

    def manager_snapshot(self) -> ExtensionManagerSnapshot:
        return ExtensionManagerSnapshot(
            pack_registry=self.pack_registry_snapshot(),
            agent_registry=self.agent_registry_snapshot(),
        )
