from __future__ import annotations

from app.agents.base import (
    ActionItemDraft,
    AgentDescriptor,
    AgentInputPayload,
    CoreAgentResult,
    CoreAnalysisAgent,
    InsightDraft,
    RecommendationDraft,
    RiskDraft,
)
from app.domain.enums import AgentCategory, AgentStatus, FlowMode
from app.model_router.base import CoreAnalysisRequest, ModelProvider


class FinanceCapitalAgent(CoreAnalysisAgent):
    descriptor = AgentDescriptor(
        agent_id="finance_capital",
        agent_type="core_analysis",
        display_name="Finance / Capital Agent",
        agent_category=AgentCategory.CORE,
        supported_task_types=["complex_convergence"],
        supported_flow_modes=[FlowMode.MULTI_AGENT],
        required_inputs=["Task", "FinancialArtifacts", "Assumption", "Evidence"],
        produced_objects=["Insight", "Risk", "Recommendation", "ActionItem"],
        default_model_policy="balanced",
        version="0.2.0",
        status=AgentStatus.ACTIVE,
    )

    def __init__(self, model_provider: ModelProvider):
        self.model_provider = model_provider

    def run(self, payload: AgentInputPayload) -> CoreAgentResult:
        response = self.model_provider.generate_core_analysis(
            CoreAnalysisRequest(
                agent_id=self.descriptor.agent_id,
                task_title=payload.title,
                task_description=payload.description,
                background_text=payload.background_text,
                goals=[goal.description for goal in payload.goals],
                constraints=[constraint.description for constraint in payload.constraints],
                evidence=[
                    {"id": evidence.id, "title": evidence.title, "content": evidence.excerpt_or_summary}
                    for evidence in payload.evidence
                ],
            )
        )
        evidence_refs = [item.id for item in payload.evidence][:3]
        return CoreAgentResult(
            findings=response.findings,
            insights=[
                InsightDraft(summary=item, evidence_refs=evidence_refs, confidence_level="medium")
                for item in response.findings
            ],
            risks=[
                RiskDraft(
                    title=f"Finance / capital risk {index + 1}",
                    description=item,
                    risk_type="financial",
                    impact_level="high" if index == 0 else "medium",
                    likelihood_level="medium",
                    evidence_refs=evidence_refs,
                )
                for index, item in enumerate(response.risks)
            ],
            recommendations=[
                RecommendationDraft(
                    summary=item,
                    rationale="Generated by the Finance / Capital Agent using the model router.",
                    based_on_refs=evidence_refs,
                    priority="high" if index == 0 else "medium",
                    owner_suggestion="Task owner",
                )
                for index, item in enumerate(response.recommendations)
            ],
            action_items=[
                ActionItemDraft(
                    description=item,
                    suggested_owner="Task owner",
                    priority="high" if index == 0 else "medium",
                )
                for index, item in enumerate(response.action_items)
            ],
            missing_information=response.missing_information,
        )
