from __future__ import annotations

from app.agents.base import (
    ActionItemDraft,
    AgentDescriptor,
    AgentInputPayload,
    CoreAgentResult,
    CoreAnalysisAgent,
    InsightDraft,
    RecommendationDraft,
    RiskDraft,
    build_payload_common_risk_context,
    build_payload_deliverable_shape_context,
    build_payload_precedent_context,
    build_payload_review_lens_context,
)
from app.domain.enums import AgentCategory, AgentStatus, FlowMode
from app.model_router.base import CoreAnalysisRequest, ModelProvider


class ResearchIntelligenceAgent(CoreAnalysisAgent):
    descriptor = AgentDescriptor(
        agent_id="research_intelligence",
        agent_type="core_analysis",
        display_name="Research / Intelligence Agent",
        agent_category=AgentCategory.CORE,
        supported_task_types=["complex_convergence"],
        supported_flow_modes=[FlowMode.MULTI_AGENT],
        required_inputs=["Task", "DecisionContext", "SourceMaterial", "Evidence"],
        produced_objects=["Insight", "Risk", "Recommendation", "ActionItem"],
        default_model_policy="balanced",
        version="0.2.0",
        status=AgentStatus.ACTIVE,
    )

    def __init__(self, model_provider: ModelProvider):
        self.model_provider = model_provider

    def run(self, payload: AgentInputPayload) -> CoreAgentResult:
        response = self.model_provider.generate_core_analysis(
            CoreAnalysisRequest(
                agent_id=self.descriptor.agent_id,
                task_title=payload.title,
                task_description=payload.description,
                response_language=payload.response_language,
                background_text=payload.background_text,
                goals=[goal.description for goal in payload.goals],
                constraints=[constraint.description for constraint in payload.constraints],
                evidence=[
                    {"id": evidence.id, "title": evidence.title, "content": evidence.excerpt_or_summary}
                    for evidence in payload.evidence
                ],
                precedent_context=build_payload_precedent_context(payload),
                review_lens_context=build_payload_review_lens_context(payload),
                common_risk_context=build_payload_common_risk_context(payload),
                deliverable_shape_context=build_payload_deliverable_shape_context(payload),
                research_depth=payload.research_depth,
                research_sub_questions=payload.research_sub_questions,
                evidence_gap_focus=payload.research_evidence_gap_focus,
            )
        )
        evidence_refs = [item.id for item in payload.evidence][:4]
        return CoreAgentResult(
            findings=response.findings,
            insights=[
                InsightDraft(summary=item, evidence_refs=evidence_refs[:2], confidence_level="medium")
                for item in response.findings
            ],
            risks=[
                RiskDraft(
                    title=f"Research / intelligence risk {index + 1}",
                    description=item,
                    risk_type="source_quality",
                    impact_level="medium",
                    likelihood_level="medium",
                    evidence_refs=evidence_refs[:2],
                )
                for index, item in enumerate(response.risks)
            ],
            recommendations=[
                RecommendationDraft(
                    summary=item,
                    rationale="Generated by the Research / Intelligence Agent using the model router.",
                    based_on_refs=evidence_refs,
                    priority="medium",
                    owner_suggestion="Task owner",
                )
                for item in response.recommendations
            ],
            action_items=[
                ActionItemDraft(
                    description=item,
                    suggested_owner="Task owner",
                    priority="medium",
                )
                for item in response.action_items
            ],
            missing_information=response.missing_information,
            research_sub_questions=response.research_sub_questions,
            source_quality_notes=response.source_quality_notes,
            contradiction_notes=response.contradiction_notes,
            evidence_gap_notes=response.evidence_gap_notes,
            citation_handoff=response.citation_handoff,
        )
