from __future__ import annotations

from app.agents.base import (
    ActionItemDraft,
    AgentDescriptor,
    AgentInputPayload,
    CoreAgentResult,
    CoreAnalysisAgent,
    RecommendationDraft,
    RiskDraft,
    build_payload_common_risk_context,
    build_payload_deliverable_shape_context,
    build_payload_deliverable_template_context,
    build_payload_domain_playbook_context,
    build_payload_organization_memory_context,
    build_payload_precedent_context,
    build_payload_review_lens_context,
)
from app.domain.enums import AgentCategory, AgentStatus, FlowMode
from app.model_router.base import CoreAnalysisRequest, ModelProvider


class RiskChallengeAgent(CoreAnalysisAgent):
    descriptor = AgentDescriptor(
        agent_id="risk_challenge",
        agent_type="core_analysis",
        display_name="Risk / Challenge Agent",
        agent_category=AgentCategory.CORE,
        supported_task_types=["complex_convergence"],
        supported_flow_modes=[FlowMode.MULTI_AGENT],
        required_inputs=["Task", "Constraint", "Evidence"],
        produced_objects=["Risk", "Recommendation", "ActionItem"],
        default_model_policy="balanced",
        version="0.1.0",
        status=AgentStatus.ACTIVE,
    )

    def __init__(self, model_provider: ModelProvider):
        self.model_provider = model_provider

    def run(self, payload: AgentInputPayload) -> CoreAgentResult:
        response = self.model_provider.generate_core_analysis(
            CoreAnalysisRequest(
                agent_id=self.descriptor.agent_id,
                task_title=payload.title,
                task_description=payload.description,
                response_language=payload.response_language,
                background_text=payload.background_text,
                goals=[goal.description for goal in payload.goals],
                constraints=[constraint.description for constraint in payload.constraints],
                evidence=[
                    {"id": evidence.id, "title": evidence.title, "content": evidence.excerpt_or_summary}
                    for evidence in payload.evidence
                ],
                organization_memory_context=build_payload_organization_memory_context(payload),
                domain_playbook_context=build_payload_domain_playbook_context(payload),
                precedent_context=build_payload_precedent_context(payload),
                review_lens_context=build_payload_review_lens_context(payload),
                common_risk_context=build_payload_common_risk_context(payload),
                deliverable_shape_context=build_payload_deliverable_shape_context(payload),
                deliverable_template_context=build_payload_deliverable_template_context(payload),
            )
        )
        evidence_refs = [item.id for item in payload.evidence][:3]
        return CoreAgentResult(
            findings=response.findings,
            risks=[
                RiskDraft(
                    title=f"Risk challenge {index + 1}",
                    description=item,
                    risk_type="challenge",
                    impact_level="medium",
                    likelihood_level="medium",
                    evidence_refs=evidence_refs,
                )
                for index, item in enumerate(response.risks)
            ],
            recommendations=[
                RecommendationDraft(
                    summary=item,
                    rationale="Generated by the Risk / Challenge Agent using the model router.",
                    based_on_refs=evidence_refs,
                    priority="medium",
                    owner_suggestion="Task owner",
                )
                for item in response.recommendations
            ],
            action_items=[
                ActionItemDraft(
                    description=item,
                    suggested_owner="Task owner",
                    priority="medium",
                )
                for item in response.action_items
            ],
            missing_information=response.missing_information,
        )
